controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

accueil:
     path: /accueil controller:App\Controller\AccueilController::index 
     
contact_submit:
     path: /contact controller:App\Controller\ContactController::submit methods:POST

show_template:
  path: /showtemplate
  controller: App\Controller\AcceuilController::showTemplate

app_feedback:
  path: '/feedback'
  controller: 'App\Controller\FeedbackController::index'

list_feedbacks:
  path: '/feedbacksList'
  controller: 'App\Controller\FeedbackController::listFeedbacks'

edit_feedback:
  path: '/edit-feedback/{id}'
  controller: 'App\Controller\FeedbackController::editFeedback'

delete_feedback:
  path: '/delete-feedback/{id}'
  controller: 'App\Controller\FeedbackController::deleteFeedback'